### ISSUE TITLE
overlayfs :)

### ISSUE THREAD

**Issue by SvenDowideit** [unclejack/debian2docker#45]

**Comment by SvenDowideit** [comment]
oh. and then I go looking to see where it builds a kernel - and realise, it doesn't.

**Comment by unclejack** [comment]
@SvenDowideit There are some problems with overlay right now in Docker. Perhaps building a kernel during build would be OK after we get overlay fixed in Docker.

There's also the backports repository for Debian, so we might be able to leverage that to avoid having to build a kernel.

**Comment by SvenDowideit** [comment]
tbh, given the goals of d2b, building a 'custom' kernel is probably not appropriate - closing as answered :)
